### ISSUE TITLE
Parse microseconds

### ISSUE THREAD

**Issue by alexpts** [MerlinDMC/fluent-plugin-input-gelf#11]
Docs: http://docs.graylog.org/en/2.4/pages/gelf.html

> timestamp:
> Seconds since UNIX epoch with optional decimal places for milliseconds; SHOULD be set by client library. Will be set to the current timestamp (now) by the server if absent.

Send data:
```json
{"version":"1.0","host":"dev-stend","short_message":"xxx","timestamp":1542298163.379436,"_ctx_timestamp":1542298163.379436}
```

Fluend std out
``` json
2018-11-15 19:09:23.000000000 +0300 dd.gelf: {"version":"1.0","host":"dev-stend","short_message":"xxx","ctx_timestamp":1542298163.379436}
```

Plugin remove microsecond and set 000000.

**Comment by alexpts** [comment]
@MerlinDMC Can you check it?

I think convert to int remove microseconds here:
```
time = record.delete('timestamp').to_i if record.key?('timestamp')

**to_i**
```

**Comment by alexpts** [comment]
@griff Can you check it?

**Comment by CarlGill** [comment]
@alexpts I just finished looking into this, and got it working ( Properly parsing subsecond time ) with the following change:

```
-        time = record.delete('timestamp').to_i if record.key?('timestamp')
+        time = Fluent::EventTime.new(record.delete('timestamp').to_f ) if record.key?('timestamp')
```
I will work on creating a branch for this.

**Comment by alexpts** [comment]
@CarlGill thanks!
I will wait new version plugin.

**Comment by alexpts** [comment]
@MerlinDMC Hi!
Can you to publish new version with fix this problem?

**Comment by MerlinDMC** [comment]
v0.3.1 has been pushed to rubygems.org
